export const PostData = [
    {
        title: '같이 밥 먹으면서 이야기할 분 있나요?????',
        content: '제가 카카오톡 그룹 만들 수 있어요! 부산 중구 주민 환영합니다 ^^',
        image: 'https://cdn.pixabay.com/photo/2017/04/08/12/59/girlfriends-2213259_1280.jpg',
        region: '경상도',
        nationality: '필리핀',
        time: 20, // 분
        likeCount: 2,
        commentCount: 5,
    },
    {
        title: '매운 음식 잘 드시나요?',
        content: '한국 김치 너무 매워요 처음 먹을 때 어떠셨어요?',
        image: null,
        region: '수도권',
        nationality: '필리핀',
        time: 60,
        likeCount: 7,
        commentCount: 3,
    },
    {
        title: '같이 밥 먹으면서 이야기할 분 있나요?',
        content: '제가 카카오톡 그룹 만들 수 있어요! 부산 중구 주민 환영합니다 ^^',
        image: 'https://cdn.pixabay.com/photo/2017/04/08/12/59/girlfriends-2213259_1280.jpg',
        region: '경상도',
        nationality: '필리핀',
        time: 20,
        likeCount: 2,
        commentCount: 5,
    },
    {
        title: '매운 음식 잘 드시나요?',
        content: '한국 김치 너무 매워요 처음 먹을 때 어떠셨어요?',
        image: null,
        region: '수도권',
        nationality: '필리핀',
        time: 60,
        likeCount: 7,
        commentCount: 3,
    },
    {
        title: '같이 밥 먹으면서 이야기할 분 있나요?',
        content: '^^',
        image: 'https://cdn.pixabay.com/photo/2017/04/08/12/59/girlfriends-2213259_1280.jpg',
        region: '경상도',
        nationality: '필리핀',
        time: 20,
        likeCount: 2,
        commentCount: 5,
    },
    {
        title: '매운 음식 잘 드시나요?',
        content: '한국 김치 너무 매워요 처음 먹을 때 어떠셨어요?',
        image: null,
        region: '수도권',
        nationality: '필리핀',
        time: 60,
        likeCount: 7,
        commentCount: 3,
    },
]